eureka:
   instance:
     preferIpAddress : true
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone : http://localhost:8761/eureka/
management:
  endpoint:
     web:
      exposure:
        include: info,  health, routes
        
spring:
   application:
     name: zuul-gateway    
       